apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wikimedia-deployment
  labels:
    app: wikimedia
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wikimedia
        type: web
    spec:
      containers:
        - name: wikimedia
          image: imanurag30/wikimedia:v1
          ports:
            - containerPort: 80
              name: httpd-port
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb-service
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbuser
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbpassword
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: dbname      