apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wikimedia-deployment
  labels:
    app: wikimedia
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wikimedia
        type: web
    spec:
      containers:
        - name: wikimedia
          image: imanurag30/wikimedia
          ports:
            - containerPort: 80
              name: httpd-port
      envFrom:
        - secretRef:
            name: mariadb-env